### ISSUE TITLE
frozen_string_literal broke assets pipeline in *.js.erb

### ISSUE THREAD

**Issue by khiav223577** [Invoca/magic_frozen_string_literal#21]
I have a js.erb file like this

```js
//= require xxxx
var xxx = <%= XXX.to_json.html_safe %>
```

after running `magic_frozen_string_literal`, it become

```js
<%# frozen_string_literal: true %>
//= require xxxx
var xxx = <%= XXX.to_json.html_safe %>
```

But the first line `<%# frozen_string_literal: true %>` seems to make `//= require xxxx` not working

**Comment by ColinDKelley** [comment]
Is the problem that the //= must be the very first line--without a newline?

We had a similar problem with XML template files. They require the XML directive to be at the very top with no blank lines.

**Comment by ColinDKelley** [comment]
@khiav223577 I think this commit should fix this bug. Can you confirm that it does?

https://github.com/Invoca/magic_frozen_string_literal/commit/fa6f96b7646fa4d5a4a5908133c92fdd281803c4

**Comment by ColinDKelley** [comment]
Assuming it's fixed unless I hear otherwise.

**Comment by khiav223577** [comment]
It doesn't work :cry: 

And I wonder if the magic comment works in `.erb` files?
I've tried
```erb
<%# frozen_string_literal: true %>
<%
a = 'test'
a << '123'
%>
```
and
```erb
<% # frozen_string_literal: true
a = 'test'
a << '123'
%>
```
Both do not raise an exception.

**Comment by ColinDKelley** [comment]
@khiav223577  Crap. Maybe magic comment doesn't work because `.erb` files are "compiled"?

In any case, given your findings, I think I should change this tool to not touch `.erb` files at all. Do you agree?

**Comment by ColinDKelley** [comment]
Fixed by removing `.erb` processing.
https://github.com/Invoca/magic_frozen_string_literal/commit/416afb1e99a11f74ec79aeed2cb0ebd54cdff2ca

**Comment by khiav223577** [comment]
Yes. I cannot find a way to make the magic comment work in erb files. (ruby 2.3.3, rails 4.2.9)
I guess it is because `.erb` files are treated as String Input to [ERB](http://ruby-doc.org/stdlib-2.5.0/libdoc/erb/rdoc/ERB.html), not as ruby script.
