### ISSUE TITLE
Immutable string literals will no longer be default in Ruby 3

### ISSUE THREAD

**Issue by jaysonvirissimo** [Invoca/magic_frozen_string_literal#30]
Per [this](https://bugs.ruby-lang.org/issues/11473) thread from 3 months ago:

> I consider this for years. I REALLY like the idea but I am sure introducing this could cause HUGE compatibility issue, even bigger than Ruby 1.9. So I officially abandon making frozen-string-literals default (for Ruby3).
> This does not mean we are going to remove the frozen-string-literal feature that can be specified by magic comments.
> Matz.

Maybe the `README` should be updated given this.

**Comment by ColinDKelley** [comment]
Thanks for pointing that out. I'm sorry to see that news. I certainly don't share Matz's pessimism that this would cause more problems than Ruby 1.9! In our experience the magic comment has worked well in quickly chasing out string mutation across gem and library boundaries without abruptly breaking anything.
But in any case, I updated the README.

**Comment by jaysonvirissimo** [comment]
Yeah, bummer.
