### ISSUE TITLE
Should Rakefile, Procfile, etc. handling be added?

### ISSUE THREAD

**Issue by HotFusionMan** [Invoca/magic_frozen_string_literal#9]
I noticed belatedly that Rakefile and other similarly-named files do not get handled.  I wonder if adding support for such files is desirable.  I think for Rakefile it may be, but likely not worthwhile for other files.

**Comment by ColinDKelley** [comment]
Rakefile seems like a good idea, since `.rake` files are processed.

**Comment by ColinDKelley** [comment]
Rakefile support added: https://github.com/Invoca/magic_frozen_string_literal/commit/11c54cca944f28ae74997042250700b98c84aeb5
